In [0]:
#Importing the libraries
import numpy as np
import torch

In [2]:
#Intialize a numpy array
a=np.array(1)

#Intialize tensor
b=torch.tensor(1)

print(a)
print(b)

1
tensor(1)


In [3]:
type(a),type(b)

(numpy.ndarray, torch.Tensor)

In [4]:
#Intialize two arrays
a=np.array(1)
b=np.array(2)
print(a,b)


1 2


In [5]:
#Mathematical Operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)

3
-1
2
0.5


In [6]:
#Intializa two tensors
a=torch.tensor(1)
b=torch.tensor(2)
print(a,b)

tensor(1) tensor(2)


In [7]:
#Mathematical Operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor(3)
tensor(-1)
tensor(2)
tensor(0)


In [9]:
#Matrix Intialization
a=np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [10]:
#Matrix Intialization
a=torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [12]:
#random seed
np.random.seed(30)

a=np.random.randn(3,3)
a

array([[-1.26405266,  1.52790535, -0.97071094],
       [ 0.47055962, -0.10069672,  0.30379318],
       [-1.72596243,  1.58509537,  0.13429659]])

In [14]:
#random seed
torch.manual_seed(30)

a=torch.randn(3,3)
a

tensor([[ 0.4705,  1.6563,  0.5153],
        [-0.2744, -2.2606,  1.2280],
        [ 0.7928,  0.6231, -2.1520]])

In [0]:
#Matrix Operations
np.random.seed(30)
a=np.random.randn(3,3)
b=np.random.randn(3,3)



In [17]:
print(np.add(a,b),'\n')
print(np.subtract(a,b),'\n')
print(np.multiply(a,b),'\n')
print(np.divide(a,b),'\n')

[[-2.37090813  3.1061309  -0.863213  ]
 [-0.29348821 -0.87588523  1.68764035]
 [-0.96557734  1.29944986  0.67266407]] 

[[-0.1571972  -0.0503202  -1.07820888]
 [ 1.23460744  0.67449179 -1.08005398]
 [-2.48634751  1.87074088 -0.40407088]] 

[[ 1.3991236   2.41137926 -0.10434943]
 [-0.35953005  0.07805894  0.42040334]
 [-1.31239609 -0.45277538  0.07230092]] 

[[ 1.14202143  0.96811597 -9.030042  ]
 [-0.61587717  0.12989965  0.21952799]
 [-2.26985308 -5.54916948  0.24945153]] 



In [18]:
print(a)
print(np.transpose(a))

[[-1.26405266  1.52790535 -0.97071094]
 [ 0.47055962 -0.10069672  0.30379318]
 [-1.72596243  1.58509537  0.13429659]]
[[-1.26405266  0.47055962 -1.72596243]
 [ 1.52790535 -0.10069672  1.58509537]
 [-0.97071094  0.30379318  0.13429659]]


In [0]:
#Matrix Operations
torch.manual_seed(30)
a=torch.randn(3,3)
b=torch.randn(3,3)

In [20]:
print(torch.add(a,b),'\n')
print(torch.sub(a,b),'\n')
print(torch.mm(a,b),'\n')
print(torch.div(a,b),'\n')

tensor([[ 0.4453,  2.6512,  0.5647],
        [-0.0863, -1.0650, -0.3315],
        [ 0.5449,  1.0686, -2.3299]]) 

tensor([[ 0.4957,  0.6614,  0.4659],
        [-0.4626, -3.4562,  2.7874],
        [ 1.0407,  0.1777, -1.9742]]) 

tensor([[ 0.1721,  2.6780, -2.6514],
        [-0.7229, -2.4287,  3.2933],
        [ 0.6308,  0.5751, -0.5498]]) 

tensor([[-18.6860,   1.6648,  10.4385],
        [ -1.4583,  -1.8907,  -0.7874],
        [ -3.1984,   1.3988,  12.0983]]) 



In [21]:
# original matrix
print(a, '\n')

# matrix transpose
torch.t(a)

tensor([[ 0.4705,  1.6563,  0.5153],
        [-0.2744, -2.2606,  1.2280],
        [ 0.7928,  0.6231, -2.1520]]) 



tensor([[ 0.4705, -0.2744,  0.7928],
        [ 1.6563, -2.2606,  0.6231],
        [ 0.5153,  1.2280, -2.1520]])

In [22]:
#Concatenating tensors
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [24]:
torch.cat((a,b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [25]:
#stacking horizontally
torch.cat((a,b),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [26]:
# setting the random seed for pytorch
torch.manual_seed(42)
# initializing tensor
a = torch.randn(2,4)
print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [27]:
# reshaping tensor
b = a.reshape(1,8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

In [28]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


In [29]:
#Autograd module
# initializing a tensor
a = torch.ones((2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [30]:
# performing operations on the tensor
b = a + 5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [31]:
# back propagating
c.backward()

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [0]:
# importing the optim module
from torch import optim

# adam
#adam = optim.Adam(model.parameters(), lr=learning_rate)